### ISSUE TITLE
No Tibber data....

### ISSUE THREAD

**Issue by mihed001** [ottopaulsen/MMM-Tibber#1]
Hi Otto,

Glad that you've developed Tibber module but i can't get it working...
See errors from log below.

/Mikael

[15:45:43.445] [ERROR]  ReferenceError: log is not defined
    at Class.readTibberPrices (/home/pi/MagicMirror/modules/MMM-Tibber/node_helper.js:34:9)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Tibber/node_helper.js:26:18)
    at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:113:11)
    at Socket.emit (events.js:182:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
[15:45:43.463] [ERROR]  (node:13171) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by ottopaulsen** [comment]
Hi

Sorry about that. I think I have fixed it now. Please update and try again.
Fun to see someone else using this. Please let me know how it works for you.
I have a bug with the current price label being cut off when it is most expensive, but I will take a look at that too.
I also just received Tibber Pulse, so I will soon develop a graph showing consumption too.

Otto

**Comment by kennethnilssen** [comment]
> Hi
> 
> Sorry about that. I think I have fixed it now. Please update and try again.
> Fun to see someone else using this. Please let me know how it works for you.
> I have a bug with the current price label being cut off when it is most expensive, but I will take a look at that too.
> I also just received Tibber Pulse, so I will soon develop a graph showing consumption too.
> 
> Otto

Hi Otto, 

Also a happy user of this tool, thx for creating this. 

Looking forward to the adjustments where the price is being cut off. Would it also be possible to center it? 
If you will add graph for showing the WATT consumption, that would be amazing. I was looking into how I can get the data from Hass.IO to MM, but have not got there yet. 
Looking forward to the update(s), keep up the good work you are doing!

**Comment by ahottesen** [comment]
Hi Otto,

First off, thanks for creating a plug-in for Tibber! Love the thought of getting this & WeConnect joined together in my upcoming smart mirror. 
But as the first guy above me here pointed out, I neither can get Tibber Data. 
I’ve tried both the “default” config and the complete you’ve attached here. 

Any clues what to test first? :-) 

Regards
Aleksander

**Comment by ottopaulsen** [comment]
Hi Aleksander

Could you please look at the logs for error messages?
I am currently doing a lot of rework on the module, so I will try to help you out. 

Otto

**Comment by kennethnilssen** [comment]
> Hi Aleksander
> 
> Could you please look at the logs for error messages?
> I am currently doing a lot of rework on the module, so I will try to help you out.
> 
> Otto

Hi,

Check out post nr 4 that helped me with the error.
https://forum.magicmirror.builders/topic/11699/mmm-tibber/4

**Comment by ahottesen** [comment]
Hi! Checked back tonight, and everythings working :-D 



> > Hi Aleksander
> > Could you please look at the logs for error messages?
> > I am currently doing a lot of rework on the module, so I will try to help you out.
> > Otto
> 
> Hi,
> 
> Check out post nr 4 that helped me with the error.
> https://forum.magicmirror.builders/topic/11699/mmm-tibber/4

Thanks, but this was already in place (guess Otto already updated the git package) :-)

**Comment by ottopaulsen** [comment]
I assume this is ok now, so I close the issue.
A new version is available, now showing historical consumption.
Please try, and let me know of any bugs.

Otto
