### ISSUE TITLE
Minor syntax error in module configuration

### ISSUE THREAD

**Issue by Stigoe** [ottopaulsen/MMM-Tibber#11]
Just to let you know that you have a small mistake in the complete module configuration example, something that threw me for a while before I noticed it.

In the complete module configuration, after 'position: "lower_third"', there is missing a comma, which gives a syntax error on the config:-line.

**Comment by ottopaulsen** [comment]
Thank you for the information, but I cannot find the code you are referring to. Are you sure it is in this repository?
Besides, the complete config is for reference purposes. You should not copy the whole thing, only those that you want to be different from the default.

Otto

**Comment by ottopaulsen** [comment]
Closing this due to no response.
