### ISSUE TITLE
Displaying savings with priceChartType: "line"

### ISSUE THREAD

**Issue by reidarw** [ottopaulsen/MMM-Tibber#19]
savingsChartType displayed as columnrange together with line as priceChartType are not suitable when adding sumAdditional in MMM-Tibber.js:noticationReceived:
![Selection_425](https://user-images.githubusercontent.com/2285954/139524700-2fd47d12-fdff-4f9e-be3f-31f86f9bf009.png)
(I changed my "Min Saver" in PowerSaver to use 0.001 to be able to view data today)
The following data is sent to the chart:
![image](https://user-images.githubusercontent.com/2285954/139525298-994fe5dd-a192-4c0b-9629-2fe92ead4e2f.png)

When not adding the sumAdditional, the chart looks fine:
![image](https://user-images.githubusercontent.com/2285954/139525323-a13ca85e-133e-4ded-84c0-11929b4a30cc.png)
This data is sent:
![image](https://user-images.githubusercontent.com/2285954/139525337-48dced9e-d1ae-47fd-84a0-6545eb7fb3b1.png)

I can change the code locally to make the graph look nice, but if you have a solution for this when you find the time, it would be nice. 

Thanks for a wonderful job with MMM-Tibber, MMM-MQTT and the Power saver!

**Comment by ottopaulsen** [comment]
Cool to se that you are using all of them :-)
Interesting bug. I am using `priceChartType: "column"`, so I am not seeing this bug.
Can you please send me you config, so I can have a look?

If you already have a fix, you could submit a PR.

**Comment by reidarw** [comment]
I did not find a optimal fix for the problem when I tried yesterday.

My config is:
  let color = {
      light_blue: '#28928c',
      blue: '#557391',
      red: '#b57e4d',
      green: '#17916a',
      grey: '#5d534a',
  };
.
.
.
        {
            module: 'MMM-Tibber',
            position: 'top_center',
            config: {
                // General
                tibberToken: 'MyToken',
                houseNumber: 0, // If you have more than one Tibber subscription
                logging: false, // Turn on to see more details, but keep normally off
                is3phase: true, // Set to true to force 3-phase
                // Chart
                historyHours: 24, // How long history for price and consumption to see in the graph
                futureHours: 48, // How long into the future to see price data
                xAxisLineColor: "#333333",
                xAxisLabelColor: "#999999",
                adjustLeftMargin: 0, // Pixels to adjust margin
                adjustRightMargin: 0,
                adjustTopMargin: 0,
                graphWidth: null, // Uses available width by default
                graphHeight: 150,
                // Savings curve
                showSavings: true,
                savingsChartType: "columnrange",
                savingsLineWidth: 3,
                savingsColor: color.light_blue,
                savingsTopic: "powersaver/plan",
                // Price curve
                showPrice: true,
                priceChartType: "line", // column, line or spline
                priceLineWidth: 3, // For line and spline, not column
                priceColor: color.blue, // For line and spline
                priceColumnColors: {
                    // Only for column chart type
                    NORMAL: ["#000055", "#0000dd", "#000088"], // Blue
                    VERY_CHEAP: ["#004400", "#00dd00", "#008800"], // Lighter green
                    CHEAP: ["#003300", "#00bb00", "#006600"], // Green
                    EXPENSIVE: ["#440000", "#cc0000", "#770000"], // Red
                    VERY_EXPENSIVE: ["#440000", "#aa0000", "#550000"], // Darker red
                    UNKNOWN: ["#444444", "#444444", "#444444"] // Gray
                },
                // Consumption curve
                showConsumption: true,
                consumptionChartType: "spline", // column, line or spline
                consumptionLineWidth: 2, // For line and spline
                consumptionColor: color.grey, // For line and spline
                consumptionDecimals: 1,
                // Price label and min/max price text
                priceUnit: "kr",
                decimalSeparator: ",",
                graphLabelFontSize: 16,
                priceDecimals: 2,
                showCurrentPrice: true,
                curPriceColor: color.green,
                // Min and Max price lines
                showMinPrice: true,
                showMaxPrice: true,
                minPriceLineWidth: 1,
                maxPriceLineWidth: 1,
                minPriceColor: color.green,
                maxPriceColor: color.red,
                adjustPriceLabelsX: 0, // Adjust position sideways in pixels (pos or neg)
                // Min/Max consumption labels
                showMinConsumption: true,
                showMaxConsumption: true,
                adjustConsumptionLabelsX: 0, // Adjust position sideways in pixels (pos or neg)
                // Additional costs
                additionalCostPerKWH: [
                    {
                        label: "Nettleie",
                        price: 0.6427
                    }
                ],
                showAdditionalCostsGraph: false,
                additionalCostsLabelColor: color.grey,
                additionalCostsLabelAdjustX: 0, // Adjust label position
                additionalCostsLabelAdjustY: 0, // Adjust label position
                includeAdditionalCostsInPrice: true,
                // Power gauge
                showPowerGauge: true,
                powerGaugeMaxValue: null, // Max gauge value. Calculated by default.
                powerGaugeMarkSize: 20, // Size of marks in % of sector area
                powerGaugeMinTickColor: color.green,
                powerGaugeAvgTickColor: color.blue,
                powerGaugeMaxTickColor: color.red,
                powerGaugeTitle: "",
                powerGaugeDynamicColors: true,
                orangePercentOfAvg: 120,
                redPowerPercentOfMax: 85,
                redPowerPercentOfAvg: 200,
                powerGaugeColors: [
                    // Colors for the graph
                    { fromValue: 0, color: color.green },
                    { fromValue: 5000, color: color.blue },
                    { fromValue: 7000, color: color.red }
                ],
                // Voltage gauge
                showVoltageGauge: false,
                voltageGaugeName: "voltage",
                voltageGaugeTitle: "",
                voltageGaugeNominalValue: 230,
                voltageGaugeMaxValue: 255,
                voltageGaugeMinValue: 150,
                voltageGaugeColors: [
                    // Colors for the graph
                    { fromValue: 0, color: color.red },
                    { fromValue: 207, color: color.blue },
                    { fromValue: 220, color: color.green },
                    { fromValue: 240, color: color.blue },
                    { fromValue: 253, color: color.red }
                ],
                // Current gauge
                showCurrentGauge: true,
                currentGaugeName: "current",
                currentGaugeTitle: "",
                currentGaugeNominalValue: 63, // Main fuse
                currentGaugeMaxValue: 70,
                currentGaugeMinValue: 0,
                currentGaugeColors: [
                    // Colors for the graph
                    { fromValue: 0, color: color.green },
                    { fromValue: 50, color: color.blue },
                    { fromValue: 61, color: color.red }
                ],
                // Gauges common
                gaugesVertical: false, // Set true to show gauges vertically
                gaugesAbove: false, // Set false to have gauges below the graph
                gaugesWidth: 230,
                gaugesHeight: 120,
                gaugesValueFontSize: 17,
                gaugesValueFontSize3phase: 14,
                gaugesValueDistanceAdjustment: 0,
                gaugesLabelFontSize: 12,
                gaugesTitleFontSize: 12,
                // Table data
                showTable: true,
                tableVertical: false,
                tableWidth: 450,
                accumulatedPowerUnit: "kWh",
                accumulatedCostCurrency: "Kr",
                tableLabelColor: color.grey,
                tableValueColor: color.grey
            }
        },

**Comment by ottopaulsen** [comment]
Ok, I haven't tried your config yet, but I found a bug when `showAdditionalCostsGraph` is false, as it is in your case. I fixed it in version 2.0.1 just now. Can you try it?

**Comment by reidarw** [comment]
![image](https://user-images.githubusercontent.com/2285954/139599760-122bc491-176a-4b12-a261-f11204351007.png)
It looks better now! Thanks!
