### ISSUE TITLE
Voltage graph shows zero

### ISSUE THREAD

**Issue by lenjak** [ottopaulsen/MMM-Tibber#24]
had Easee Home and Watty installed about 2 weeks ago. At the same time I installed MMM-Tibber. The Tibber subscription started today, 13 Jan.

For the first 2-3 days MagicMirror showed info in the Voltage graph. But after that it shows 0 for all 3 phases

Being a noob about raspberry/magic mirror,etc
I don’t understand if it is Watty or MMM-Tibber

Tested with only the Tibber token in the config,
But also with other options
I have restarted Watty several times

To me it seems like the Tibber/Watty app has correct info altough it doesn’t shows voltage

**Comment by ottopaulsen** [comment]
Can you see voltage in the Tibber app?

If so, go to the [Tibber API explorer](https://developer.tibber.com/explorer), load your personal token, select "Real time subscription", add voltagePhase1, voltagePhase2 and voltagePhase3 to the list and run.
Verify that you see voltage for all phases in the result.
For me, voltage shows values briefly every 8-10 seconds, and just null in between, but as long as values are shown, it should be enough.

**Comment by lenjak** [comment]
Wow, quick response ;-)

I got this:

{
  "liveMeasurement": {
    "timestamp": "2022-01-13T09:18:21.500+01:00",
    "power": 1284.8,
    "accumulatedConsumption": 21.368371,
    "accumulatedCost": 0,
    "currency": "SEK",
    "minPower": 824.9,
    "averagePower": 2296.2,
    "maxPower": 6167.5
  }
}

**Comment by lenjak** [comment]
Sorry forgot the voltagePhases

{
  "liveMeasurement": {
    "timestamp": "2022-01-13T09:21:06.500+01:00",
    "power": 3724,
    "accumulatedConsumption": 21.489501,
    "accumulatedCost": 0,
    "currency": "SEK",
    "minPower": 824.9,
    "averagePower": 2297.9,
    "maxPower": 6167.5,
    "voltagePhase1": null,
    "voltagePhase2": null,
    "voltagePhase3": null
  }
}

**Comment by lenjak** [comment]
I have emailed Tibber support with questions
I will give you feedback when they respond
Thanx for excellent support 😁

**Comment by ottopaulsen** [comment]
So if you get null all the time, the problem is not in the MMM-Tibber module.

**Comment by lenjak** [comment]
Agree, I watched it for 5 minutes and it statyed at null all the time
Already emailed Tibber but they are not quick to respond

If you want me to I can keep the  issue open and feedback if/when they answer
As far as I can see the Tibber app hasn't any field for Voltage so I guess it's either Watty or their API

**Comment by lenjak** [comment]
I rest my case😎
Tibber did not respond so I had to remind them
And then they did not react to the fact that their API showed ”null”
I had to restart Easee and Watty at one time for other reason and then the Tibber API showed som value for some minutes and then it was back to null
But I am happy with your module the way it works so thanks for your module Otto 👍
Closing…
