### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by gitsemsch** [ottopaulsen/MMM-Tibber#25]
Hi Otto.

MMM-Tibber is a great piece of work so big thanks to you.
Is it possible to change the background color easily in the CCS file or some other way?
I would like to have it partly transparant if possible so that it matches all other modules on the magicmirror screen.

thanks

**Comment by ottopaulsen** [comment]
I think this can be solved by [configuring background color](https://api.highcharts.com/highcharts/chart.backgroundColor) with a pattern object.
But it requires coding.

**Comment by Snille** [comment]
I think the easiest way is to add the following to your custom.css
```CSS
.MMM-Tibber .highcharts-background {
  opacity: 0;
} 
```
That works for me atleast. :)

**Comment by gitsemsch** [comment]
Thanks

tir. 20. feb. 2024, 08:21 skrev Erik Pettersson ***@***.***>:

**Comment by ottopaulsen** [comment]
Great! Closing.
