### ISSUE TITLE
Additional costs

### ISSUE THREAD

**Issue by mickegranath** [ottopaulsen/MMM-Tibber#26]
Maybe I'm doing somethin wrong, but when I adding additional costs the price label returns Nan,NO kr. I entered i like this: additionalCostPerKWH: [0.74],

**Comment by ottopaulsen** [comment]
If you see the documentation for additional costs, you can see tghat it shall be configured like this:
```js
    additionalCostPerKWH: [
      {
        label: "Nettleie",
        price: 0.23125
      },
      {
        label: "Forbruksavgift",
        price: 0.20163
      }
    ],
```

**Comment by mickegranath** [comment]
Thanks, I missed that.

Micke
