### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by mbranell** [ottopaulsen/MMM-Tibber#27]
The code "se" is not correct. Should be "sv". se shows Serbian language i think, Any way, se shows not Swedish language.

**Comment by ottopaulsen** [comment]
What are you referring to?

**Comment by Svanto1963** [comment]
the translations file se.json dosent show sewdish language. Most be SV not SE

**Comment by retroflex** [comment]
Just found out the same. Just to clarify @ottopaulsen the needed change is to rename se.json -> sv.json + changing in the getTranslations method. I tried it now and it works fine. Maybe I have some time to do a PR in case that would help.

**Comment by Svanto1963** [comment]
how/where do you "changing in the getTranslations method" ??
