### ISSUE TITLE
Dependencies decreated (Apollo Server)

### ISSUE THREAD

**Issue by seomranea** [ottopaulsen/MMM-Tibber#29]
I'm trying to install the MMM-Tibber but encoutered dependency issue with Apollo Server 3. Here are the errors I got:

npm WARN deprecated aws-lambda@0.1.2: please upgrade to latest 1.x
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated apollo-tracing@0.1.4: The `apollo-tracing` package is no longer part of Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#tracing for details
npm WARN deprecated graphql-extensions@0.0.10: The `graphql-extensions` API has been removed from Apollo Server 3. Use the plugin API instead: https://www.apollographql.com/docs/apollo-server/integrations/plugins/
npm WARN deprecated apollo-tracing@0.1.4: The `apollo-tracing` package is no longer part of Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#tracing for details
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout

Thanks for any suggestion.

**Comment by ottopaulsen** [comment]
I have updated dependencies today, in version `2.1.1`.
Please try.

**Comment by seomranea** [comment]
Great, it works, thanks for resolving it so quickly.
