### ISSUE TITLE
Update Interval

### ISSUE THREAD

**Issue by Spitzoo** [ottopaulsen/MMM-Tibber#30]
Is it possible to change the Update Interval?
Tibber recently added a rate limit of 100 requests in 5 minutes per IP address to protect the API.
I'm now getting "No Tibber data" when using my Tibber token. Works fine with their demo token.

**Comment by ottopaulsen** [comment]
The update interval is 1 per minute, so you must have another issue.

**Comment by ottopaulsen** [comment]
Anyway, if you update to version 2.1, you can set the update interval using the `updateInterval` config parameter. See doc.

**Comment by Twokidsfather** [comment]
Hur uppdatera man din modul?

**Comment by ottopaulsen** [comment]
cd MagicMirror/modules/MMM-Tibber
git pull
# eller
npm install
