### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by andzie82** [ottopaulsen/MMM-Tibber#37]
The log’s shows the below, which’s why the graphics does not display I guess. 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: mmm-tibber@2.1.2
npm ERR! Found: graphql@14.7.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"^14.7.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^15.2.0 || ^16.0.0" from graphql-yoga@2.13.13
npm ERR! node_modules/graphql-yoga
npm ERR!   graphql-yoga@"^2.13.13" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/pi/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-10-06T22_06_05_991Z-debug-0.log

**Comment by ottopaulsen** [comment]
Try running npm install

**Comment by Mazze83** [comment]
Same issue on a fresh install

pi@mirror:~/MagicMirror/modules/MMM-Tibber $ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: graphql-yoga@2.13.13
npm ERR! Found: graphql@14.7.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"^14.7.0" from the root project
npm ERR!   peer graphql@"^14.0.0 || ^15.0.0 || ^16.0.0" from @envelop/core@2.6.0
npm ERR!   node_modules/@envelop/core
npm ERR!     peer @envelop/core@"^2.6.0" from @envelop/parser-cache@4.7.0
npm ERR!     node_modules/@envelop/parser-cache
npm ERR!       @envelop/parser-cache@"^4.6.0" from @graphql-yoga/common@2.12.12
npm ERR!       node_modules/graphql-yoga/node_modules/@graphql-yoga/node/node_modules/@graphql-yoga/common
npm ERR!         @graphql-yoga/common@"^2.12.12" from @graphql-yoga/node@2.13.13
npm ERR!         node_modules/graphql-yoga/node_modules/@graphql-yoga/node
npm ERR!     peer @envelop/core@"^2.6.0" from @envelop/validation-cache@4.7.0
npm ERR!     node_modules/@envelop/validation-cache
npm ERR!       @envelop/validation-cache@"^4.6.0" from @graphql-yoga/common@2.12.12
npm ERR!       node_modules/graphql-yoga/node_modules/@graphql-yoga/node/node_modules/@graphql-yoga/common
npm ERR!         @graphql-yoga/common@"^2.12.12" from @graphql-yoga/node@2.13.13
npm ERR!         node_modules/graphql-yoga/node_modules/@graphql-yoga/node
npm ERR!     2 more (@graphql-yoga/node, @graphql-yoga/common)
npm ERR!   21 more (@envelop/parser-cache, @envelop/types, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^15.2.0 || ^16.0.0" from graphql-yoga@2.13.13
npm ERR! node_modules/graphql-yoga
npm ERR!   graphql-yoga@"^2.13.13" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: graphql@16.6.0
npm ERR! node_modules/graphql
npm ERR!   peer graphql@"^15.2.0 || ^16.0.0" from graphql-yoga@2.13.13
npm ERR!   node_modules/graphql-yoga
npm ERR!     graphql-yoga@"^2.13.13" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/pi/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-10-07T09_43_11_858Z-debug-0.log

**Comment by andzie82** [comment]
> Try running npm install

That alone didn’t work but a few updates and force command it’s now working.
