### ISSUE TITLE
No value in "Cost today"

### ISSUE THREAD

**Issue by kennethnilssen** [ottopaulsen/MMM-Tibber#4]
Hi, 

First, I´m the one tipping of Tibber what your cool code can do, and ensured they wrote about your code:
https://tibber.com/no/magazine/power-hacks/magic-mirror-smartspeil

One issue, and I cannot find where in the code to change it, if the "Cost today" is under 0, it will not show anything.

- Can you point out where in the code, so the price will show up to 2 decimal? So the "Cost today" will i.e. show 0,14 Kr? The price per kWh is so low that it ends up at 0 all day long ;) 

- Would it also be possible to show the "Month so far" tab?

Thx for creating amazing code!

**Comment by kennethnilssen** [comment]
Solved one of two questions in this issue:

![image](https://user-images.githubusercontent.com/60935848/88638386-b9081d80-d0bb-11ea-93dc-7f0d71d134fd.png)

From file: MMM-Tibber.js, at line 471:

`    accumulatedCost.innerHTML = (
      subData.accumulatedCost.toFixed(2) +
        (this.config.includeAdditionalCostsInPrice
          ? sumAdditionalCosts(this.config) * subData.accumulatedConsumption
          : 0)
    );`

**Comment by ottopaulsen** [comment]
Hi Kenneth, and sorry for the extremely late response. I have been on vacation and have not had any time for this.
Thanks for the change suggestion I will include it in my next release, whenever that will be :-)

About the month so far, I will keep this open, but I will have very little time in the next few months, so it would not be any time soon.

**Comment by kennethnilssen** [comment]
No worries Otto, and thx for getting back to me. 

I just altered my code as I wanted to see the "cost today" when it is below 1 NOK ;) 

See what you can do/ find the time for, and if I find something, I will let you know.
