### ISSUE TITLE
Sluttet plutselig å få inn data fra pulse.

### ISSUE THREAD

**Issue by Timaor** [ottopaulsen/MMM-Tibber#45]
Får opp denne feilen i loggen.

0|mm  | [05.01.2023 22:26.13.262] [ERROR] Tibber socker error:  Error: Unexpected server response: 404
0|mm  |     at ClientRequest.<anonymous> (/home/pi/MagicMirror/modules/MMM-Tibber/node_modules/ws/lib/websocket.js:886:7)
0|mm  |     at ClientRequest.emit (node:events:513:28)
0|mm  |     at HTTPParser.parserOnIncomingClient (node:_http_client:674:27)
0|mm  |     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
0|mm  |     at TLSSocket.socketOnData (node:_http_client:521:22)
0|mm  |     at TLSSocket.emit (node:events:513:28)
0|mm  |     at addChunk (node:internal/streams/readable:315:12)
0|mm  |     at readableAddChunk (node:internal/streams/readable:289:9)
0|mm  |     at Readable.push (node:internal/streams/readable:228:10)
0|mm  |     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
0|mm  | [05.01.2023 22:26.13.262] [ERROR] Closing Tibber socket
0|mm  | [05.01.2023 22:26.13.263] [LOG]   Tibber socket disconnected unexpectingly. Reconnecting in 45 seconds.

**Comment by ottopaulsen** [comment]
Tibber har endret protokoll.
Jeg jobber med saken.

**Comment by Timaor** [comment]
Ja så det nå på Tibber developer siden :)

**Comment by crazyfroggers81** [comment]
Fantastisk :) 

Benytter anledningen til å si at denne modulen er helt konge. Gleder meg til å se live data igjen på Magicmirroren :)

**Comment by Timaor** [comment]
> Fantastisk :)
> 
> Benytter anledningen til å si at denne modulen er helt konge. Gleder meg til å se live data igjen på Magicmirroren :)

Helt enig! Denne modulen til MM har fått både kone og barn til å være mer bevist på strømbruk. Veldig kjekt nå som strømmen er så "billig".

**Comment by ottopaulsen** [comment]
Please try version 3.0.0. It shall work now.
Please note that you now must configure `homeId` instead of `homeNumber`.
You can find your homeId by logging in to https://developer.tibber.com/explorer, 
loading your personal token and running the following query:

```
{
  viewer {
    homes {
      id
      address {
        address1
        address2
        address3
        postalCode
        city
        country
      }
    }
  }
}
```

Use the value for the `id` of the correct home as `homeId` in the config.

**Comment by Hakonbe** [comment]
I just updated to 3.0.0 and entered the homeId
I found, into the configuration
{
    module: 'MMM-Tibber',
    position: 'bottom_center',
    config: {
        tibberToken: '<find your token from tibber.com>'
        homeId: '<see below how to find your home id>'
    }
},
But then MM stopped working. When I comment out the line with homeId MM are working again but obviously with no Tibber data.
I'm I missing something?

**Comment by ottopaulsen** [comment]
Missing comma after homeId.

**Comment by Hakonbe** [comment]
Thank you so much. Just a little comma..

**Comment by Timaor** [comment]
Thanks @ottopaulsen! The module still crashes sometimes. Freezes up. Any clue what it could be?

**Comment by ottopaulsen** [comment]
No, I am still trying it out myself. Please let me know if you find out anything.

**Comment by Timaor** [comment]
I get this error constantly.

0|MagicMirror  | [19.01.2023 05:44.10.447] [LOG]   User-Agent: MMM-Tibber/2.22.0 (linux; Node.js/v16.17.1)
0|MagicMirror  | [19.01.2023 05:44.10.469] [LOG]   Initializing WebSocket
0|MagicMirror  | [19.01.2023 05:44.10.844] [LOG]   Tibber WebSocket closed
0|MagicMirror  | [19.01.2023 05:44.30.457] [LOG]   Reconnecting in 57 seconds
