### ISSUE TITLE
Causes black screen after updating to V.2.22.0

### ISSUE THREAD

**Issue by Lazershrimp** [ottopaulsen/MMM-Tibber#46]
Hi!

After updating MagicMirror2 to version 2.22.00, I started getting major problems. I got a new sd card, reinstalled and updated Raspbian and MagicMirror, and have narrowed the problem down to the MMM-Tibber module. 

When the module is "active", that is when the MMM-Tibber part is in the config file, the MagicMirror just shows a black screen. If I "double slash" the Tibber module part in the config file, all works well. When installing the module, I get a lot of error codes after "npm install". Please bear with me, since I am not very good at programming. This is what it says:

pi@raspberrypi:~/MagicMirror/modules/MMM-Tibber $ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: graphql-yoga@2.13.13
npm ERR! Found: graphql@14.7.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"^14.7.0" from the root project
npm ERR!   peer graphql@"^14.0.0 || ^15.0.0 || ^16.0.0" from @envelop/core@2.6.0
npm ERR!   node_modules/@envelop/core
npm ERR!     peer @envelop/core@"^2.6.0" from @envelop/parser-cache@4.7.0
npm ERR!     node_modules/@envelop/parser-cache
npm ERR!       @envelop/parser-cache@"^4.6.0" from @graphql-yoga/common@2.12.12
npm ERR!       node_modules/graphql-yoga/node_modules/@graphql-yoga/node/node_modules/@graphql-yoga/common
npm ERR!         @graphql-yoga/common@"^2.12.12" from @graphql-yoga/node@2.13.13
npm ERR!         node_modules/graphql-yoga/node_modules/@graphql-yoga/node
npm ERR!     peer @envelop/core@"^2.6.0" from @envelop/validation-cache@4.7.0
npm ERR!     node_modules/@envelop/validation-cache
npm ERR!       @envelop/validation-cache@"^4.6.0" from @graphql-yoga/common@2.12.12
npm ERR!       node_modules/graphql-yoga/node_modules/@graphql-yoga/node/node_modules/@graphql-yoga/common
npm ERR!         @graphql-yoga/common@"^2.12.12" from @graphql-yoga/node@2.13.13
npm ERR!         node_modules/graphql-yoga/node_modules/@graphql-yoga/node
npm ERR!     2 more (@graphql-yoga/node, @graphql-yoga/common)
npm ERR!   21 more (@envelop/parser-cache, @envelop/types, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^15.2.0 || ^16.0.0" from graphql-yoga@2.13.13
npm ERR! node_modules/graphql-yoga
npm ERR!   graphql-yoga@"^2.13.13" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: graphql@16.6.0
npm ERR! node_modules/graphql
npm ERR!   peer graphql@"^15.2.0 || ^16.0.0" from graphql-yoga@2.13.13
npm ERR!   node_modules/graphql-yoga
npm ERR!     graphql-yoga@"^2.13.13" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/pi/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2023-01-06T22_34_44_323Z-debug-0.log

Can you help me? I really like this module!

**Comment by Timaor** [comment]
Been struggling with black screen as well. I have the same error. Usually a quick restart of MM solves the problem for me. But it's not a temporary fix as it goes black after a while. Tried updating the dependencies, still the same error. Hoping for a fix :)

**Comment by ottopaulsen** [comment]
Please try version 3.0.0. It shall work now.
Please note that you now must configure `homeId` instead of `homeNumber`.
You can find your homeId by logging in to https://developer.tibber.com/explorer, 
loading your personal token and running the following query:

```
{
  viewer {
    homes {
      id
      address {
        address1
        address2
        address3
        postalCode
        city
        country
      }
    }
  }
}
```

Use the value for the `id` of the correct home as `homeId` in the config.

**Comment by ottopaulsen** [comment]
Closing due to no response.
