### ISSUE TITLE
Illegal Tibber token

### ISSUE THREAD

**Issue by ginatrick** [ottopaulsen/MMM-Tibber#47]
I get always the Message:
[ERROR] ERROR: Illegal Tibber token. Please sign in to developer.tibber.com to get correct token, and update the modules config.

But if i launch: node get-homes.js <tibberToken> i get my Home Id .. so i thnik my Token ist correct. What can i do?

**Comment by andzie82** [comment]
Did you get your token from the developer site?

**Comment by ginatrick** [comment]
> Did you get your token from the developer site? If so it sounds like you got the demo token?

No it's my personal token. Otherwise i dont get the right Home ID

**Comment by andzie82** [comment]
Well, how do you know it’s your HomeId and not the Demo Tokens?

Do you get your personal details when you use it in Tibbers API Query?

**Comment by ginatrick** [comment]
Yes i got all my personal data in the API Explorer.

**Comment by hittapanagot** [comment]
Hi.

I got the same error message and checked with Tibber and it´s connected to your account.
The data will not be visible until the agreement is valid.

**Comment by TheoSnitch** [comment]
Does anyone have a fix to this? I get this error when trying to start: 
[Error] ERROR: Illegal Tibber token. Please sign in to developer.tibber.com to get correct token, and update the modules config.

**Comment by ottopaulsen** [comment]
I am closing this, as it seems to be no problem with the module.
