### ISSUE TITLE
Power gauge doesn't work

### ISSUE THREAD

**Issue by TheKnappen** [ottopaulsen/MMM-Tibber#50]
I just updated to the latest update and now the power gauge and A gauge doesn't work. I haven't changed anything in the config.

As you can see the other data loads in but not the gauge data that worked before the update.

![PXL_20230303_181905893](https://user-images.githubusercontent.com/96777194/222797367-fa4e75eb-0f27-481b-b687-59a947401db7.jpg)

**Comment by avolaid** [comment]
Same problem here :(

**Comment by ottopaulsen** [comment]
Did you configure homeId as described in the documentation?
This is a breaking change in version 3.0

**Comment by TheKnappen** [comment]
Yes I've set my homeID through the API.

Alexander Knapköyen

Den sön 5 mars 2023 09:32Otto Paulsen ***@***.***> skrev:

**Comment by avolaid** [comment]
I found the solution. Delete Access Token and generate new one. Now use the new Access Token key. It works for me
