### ISSUE TITLE
/home/pi/MagicMirror/config/config.js:47         homeId: 

### ISSUE THREAD

**Issue by lbundgaard** [ottopaulsen/MMM-Tibber#51]
syntax error. homeId 
 Please correct syntax errors at or above this line: /home/pi/MagicMirror/config/config.js:47

modules: 

		{
    module: 'MMM-Tibber',
    position: 'bottom_center',
    config: {
        tibberToken: "my token"
        homeId: "1...my long home id...3"
    }
},

**Comment by ottopaulsen** [comment]
You are missing a comma at the end of the tibberToken line.

**Comment by lbundgaard** [comment]
thanks, now it works.
