### ISSUE TITLE
Dynamic Min level

### ISSUE THREAD

**Issue by wuast94** [ottopaulsen/MMM-Tibber#55]
Would be nice to have an option to not start price lvl by 0. 

If its based on the minPrice the graph looks not so flat and shows better when its a high or a low price.

It could also be a offset of minPrice. for example if the minPrice is 0.25 and the offset is 0.1 the graph would start at 0.15

**Comment by ottopaulsen** [comment]
Good idea. I have made it.
Install the latest version and set the config value `dynamicMin` to e.g. `0.1`.
Please let me know how it works.

**Comment by wuast94** [comment]
looks way better now, thanks for the fast response and work 😊
