### ISSUE TITLE
Help request getting Home Id

### ISSUE THREAD

**Issue by madebywitteveen** [ottopaulsen/MMM-Tibber#62]
Hi,

could you be so kind to give a bit more explanation how to get the Home Id for Tibber API ?
first; where should I run the get-home.js ? in node red or in Powershell on my computer ?
Tried both but can't get it to work

Thank you and best regards

**Comment by ottopaulsen** [comment]
Did you read the documentation?
Make sure you can use the [Tibber API Explorer](https://developer.tibber.com/explorer), and run e.g. this script:
```
{
  viewer {
    homes {
      id
      address {
        address1
      }
    }
  }
}
```

**Comment by madebywitteveen** [comment]
Thanks a lot! That is working now I have my home ID.

But; how to get the 'price-level' attribute in node-red with the Tibber plugins ?
The price-level attribute goes from Cheap to Normal to Expensive

thanks again

**Comment by ottopaulsen** [comment]
Sorry, I do not understand your question.
